name: Pipeline to build on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        run: echo "Hello, world!"

      - name: Install dependencies
        run: npm install

      - name: Print working directory
        run: pwd

      - name: List all the files
        run: ls -R packages/db/prisma

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Run Build
        run: npm run build
